### ISSUE TITLE
The drawing will be shifted to the right instead of at the specified position. What is the situation

### ISSUE THREAD

**Issue by A-lie** [NorthwoodsSoftware/GoJS#109]
The first drag out is not at the specified position, but will offset to the right. You need to drag again

**Comment by WalterNorthwoods** [comment]
I am closing this because you do not appear to be reporting a bug nor do you provide a minimal reproducible example demonstrating the problem that you have nor even some screenshots.  Ask about your problem in the forum.

**Comment by A-lie** [comment]
![~SHP4$(FOKQ$C79Z4RR21KU](https://user-images.githubusercontent.com/55788805/91919019-35af9c80-ecf7-11ea-9ff5-a563f2951fcb.png)

**Comment by A-lie** [comment]
[addInfos.zip](https://github.com/NorthwoodsSoftware/GoJS/files/5159418/addInfos.zip)
