### ISSUE TITLE
How textBlocks sets the line height of the text font？

### ISSUE THREAD

**Issue by xiongchaohu** [NorthwoodsSoftware/GoJS#112]
How textBlocks sets the line height of the text font？

**Comment by simonsarris** [comment]
They cannot directly, but it can be adjusted by setting either the textBlock.height (if one line), or else the `textBlock.spacingAbove` and `textBlock.spacingBelow` (both numbers that default to zero)

These are undocumented properties.

Please use the [forum](https://forum.nwoods.com/) for any other support questions.
