### ISSUE TITLE
vue3   erorr:  EnumValue.Default is not a valid geometryStretch.

### ISSUE THREAD

**Issue by wowoName** [NorthwoodsSoftware/GoJS#114]
![image](https://user-images.githubusercontent.com/32700497/97380958-0d14df00-1903-11eb-8b44-c78193f0733e.png)

**Comment by WalterNorthwoods** [comment]
Could you please tell us how to reproduce the problem in a minimal sample?

**Comment by wowoName** [comment]
I wonder what caused it. I'm putting the    go.graphobject. Make    instance object into ref. I'll save the instance object using a variable instead. 
Thank you very much

**Comment by tandrew** [comment]
The solution to this is to NOT use a reactive vue3 variable for the diagram. In vue2 this was possible (but not necessary either for goJS). 

In vue3 this has changed and no longer works. Just define your diagram variable as non-reactive. If you are still using the vue2 Options API in a vue3 context you can just do `this.$options.diagram = ...`

**Comment by sahith-modak** [comment]
@tandrew Hi, I am facing the same issue, I am using the vue2 Options API in vue, can you explain, how to remove reactivity with an example?

**Comment by WalterNorthwoods** [comment]
I suggest instead starting from https://github.com/NorthwoodsSoftware/gojs-vue-basic.
That uses Vue 3.

**Comment by sahith-modak** [comment]
@WalterNorthwoods  @tandrew  we are migrating from vue 2 to vue 3, In vue2 the code is working fine, I am facing the issue only with vue 3.

**Comment by tandrew** [comment]
I am using the composition API. 

```javascript
import go, {
    ChangedEvent,
    Diagram, // -> see below
    DiagramEvent,
    GraphLinksModel,
    GraphObject,
    InputEvent,
    Part,
} from 'gojs';

...

// reactive
const divDiagram = ref(); // Reference to html div container for diagram 

// non-reactive
const $ = go.GraphObject.make; // shortcut to "make"
let diagram: Diagram | null = null; // this will hold the diagram object

onMounted (() =>
    diagram = $(go.Diagram, divDiagram.value, {

        layout: $(go.LayeredDigraphLayout, {
            isInitial: false,
...
      }
)


```

HTH!
