### ISSUE TITLE
Questions about milestones

### ISSUE THREAD

**Issue by Xieguoiang** [NorthwoodsSoftware/GoJS#115]
hello,
I would like to ask whether the layout algorithm is considered to be separated in the future?

I want to split the algorithm and rendering into threads。

thanks!

**Comment by WalterNorthwoods** [comment]
Having the layout optionally run in a web worker has been on our list of things to do.

As far as rendering in a different thread is concerned, that may become more possible in the near future: https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas
But until then, that will be a lower priority.

**Comment by WalterNorthwoods** [comment]
There is now internal support for having **ForceDirectedLayout** and **LayeredDigraphLayout** to run in a web worker.  But it's a bit finicky to use, and it doesn't handle all of the options for **LayeredDigraphLayout**.
