### ISSUE TITLE
Hello, brother. How to update the view using gojs in Vue. When the requested data is re rendered, an error is reported: invalid div ID; div already has a diagram associated with it. I am looking forward to your reply. Thank you

### ISSUE THREAD

**Issue by wpc124** [NorthwoodsSoftware/GoJS#117]
Please do not use the GitHub issue tracker unless you are reporting a bug in GoJS,
not a problem in your code nor a question about how to do something or use something.

For help and support, please use the GoJS forum: https://forum.nwoods.com/c/gojs

**Comment by WalterNorthwoods** [comment]
Don't create a second Diagram, nor a second Model, when you want to re-render.

This is not a bug in GoJS,  so you should not be asking questions here.
