### ISSUE TITLE
samples/customContextMenu.html Eventlisteners

### ISSUE THREAD

**Issue by martienvlent** [NorthwoodsSoftware/GoJS#13]
samples/customContextMenu.html

The blur listener can not work. Currently, the context menu is stopped internally by GoJS' commandHandler / background click handler.
If you want the contextMenuTool to stop by an element outside the canvas gaining focus, the menu should gain focus in the first place, before it can fire blur.

A possible scenario:
1. allow for the menu div to gain focus by setting tabindex="1" and set focus in the contextmenu eventhandler. 
2. prevent the links inside from taking over focus - use onclick on de li-elements, like so: `<li id="cut" onclick="cxcommand(this.textContent);">Cut</li>` - otherwise, the menu blur will stop the tool before any click can be handled.
3. adjust the stylesheet accordingly
4. put the eventlisteners after the cxTool declaration and change to:

	cxElement.addEventListener("contextmenu", function(e) { this.focus(); e.preventDefault(); return false; }, false );
	cxElement.addEventListener("blur", function(e) { cxTool.stopTool() }, false);

Regars, Martien van Lent

**Comment by simonsarris** [comment]
I see what you mean. I've taken your suggestions and improved the sample, thanks.

Those changes will be out with GoJS 1.6's next beta release, but we are not going to update it for the 1.5 branch.
