### ISSUE TITLE
How to remove the upper left corner watermark

### ISSUE THREAD

**Issue by janice-xu** [NorthwoodsSoftware/GoJS#130]
Please do not use the GitHub issue tracker unless you are reporting a bug in GoJS,
not a problem in your code nor a question about how to do something or use something.

For help and support, please use the GoJS forum: https://forum.nwoods.com/c/gojs

How to remove the upper left corner watermark？

**Comment by WalterNorthwoods** [comment]
Purchase a license at: https://www.nwoods.com/sales/index.html
The process is described at: https://gojs.net/latest/intro/deployment.html
