### ISSUE TITLE
Relinking tool does not work fine when moving link to nodes that are already connected

### ISSUE THREAD

**Issue by violarodrigues-dataworld** [NorthwoodsSoftware/GoJS#133]
In the image below, I am trying to move the link  existing between Alpha and Gamma to Alpha and Beta using Relinking tool. But this relinking is not made possible.
![image](https://user-images.githubusercontent.com/55781150/112262667-06ad4800-8c94-11eb-8f65-8ba22e84f44a.png)

**Comment by WalterNorthwoods** [comment]
That is probably because you have not enabled allowing duplicate links between nodes.
Please read https://gojs.net/latest/intro/validation.html
