### ISSUE TITLE
Possible regression in setKeyForNodeData

### ISSUE THREAD

**Issue by rwynn** [NorthwoodsSoftware/GoJS#14]
When testing an upgrade from 1.4.27 to 1.5.20 I noticed a change in behaviour for go.Model.setKeyForNodeData.  

Specifically, when the node has connected Links and the node key is changed, the connected link data (to/from attributes) are either updated (1.4.27) or not updated (1.5.20) accordingly.  

Please see attached test to replicate.  

[index.html.zip](https://github.com/NorthwoodsSoftware/GoJS/files/129994/index.html.zip)

**Comment by WalterNorthwoods** [comment]
Thanks for reporting this bug.  Yes, the link data should have been modified.  This will be fixed in 1.5.21, which we'll release later this week.  (Today's a holiday, actually.)
