### ISSUE TITLE
Context menu options do not appear

### ISSUE THREAD

**Issue by hmorkonda** [NorthwoodsSoftware/GoJS#148]
https://gojs.net/latest/learn/interactivity.html#ContextMenus

The context menu options do not appear on right click of the node even inside the sample canvas. Only "click me" button and prompt works. Please verify.

**Comment by WalterNorthwoods** [comment]
I am unable to notice any problems with context menus in that example, in two different browsers on two different platforms.  Could you please tell us precisely how to reproduce a problem?
