### ISSUE TITLE
When you press Delete to delete a connector between nodes, is there a callback method to know which connector is currently deleted?

### ISSUE THREAD

**Issue by Sparkle-Bo** [NorthwoodsSoftware/GoJS#149]
this.myDiagram.commandHandler.deleteSelection = function () { to do something }
This method has no callback parameters and does not know which connection line is currently deleted

**Comment by simonsarris** [comment]
You can use the `"SelectionDeleted"` Diagram Event:

https://gojs.net/latest/intro/events.html#SelectionDeleted

For example:
```
      myDiagram.addDiagramListener("SelectionDeleted", function(e) {
        e.subject.each(function(obj) {
          // do something with each deleted obj
        });
      });
```

Do not use this issue tracker for support. Use the [Forum](https://forum.nwoods.com/c/gojs/11)
