### ISSUE TITLE
How can I create a new node when I drag a link as soon as I release my mouse?

### ISSUE THREAD

**Issue by xinnai** [NorthwoodsSoftware/GoJS#152]
Hi, thank you for your hard work, I have some problems when using 'gojs'.
I found that when I drag a link from a node which already in canvas, I must drag it onto another node, otherwise the link will disappear when I release my mouse. How can I create a new node when I drag a link as soon as I release my mouse, and make  the new node just at the place where the 'mouse up', and also make the link linkto the new node automatically?
Thank you !

**Comment by simonsarris** [comment]
Please use the [support forum](https://forum.nwoods.com/c/gojs/11) for support questions, not the issue tracker.
