### ISSUE TITLE
Group's location that have priority over Node's location

### ISSUE THREAD

**Issue by senese** [NorthwoodsSoftware/GoJS#160]
I am developing a GoJS Diagram based on the Leaflet example. That means that redraw and updateAllTargetBindings methods are included (on any move event). My diagram though has groups that expand/collapses their placeholders with a certain zoom level.

As I looked up on GoJS forum, when groups have Placeholders their locations are ignored in favor of nodes locations. This logic causes an odd behaviour that when the zoom in or zoom out happens, the redraw() method causes the group location binding be considered for a brief moment and then node location binding takes place.

So you can imagine that in this example the group Lat-Long is more important than the node Lat-Long, but the Placeholder is still very important because it can be dinamically resized depending on the number of children nodes.

With group location having priority, the developer doesn't have to assign any location to a node. So my propose here is to create a property that makes group's location prevail over node's location.

**Comment by WalterNorthwoods** [comment]
The whole purpose of a Placeholder is to position and size the Group based on the group's members.
If you want the position/location of a Group to be independent of its members, don't use a Placeholder.
If you want the size to depend on the members somehow, implement it yourself.
https://gojs.net/latest/intro/sizedGroups.html
For a completely different scenario:
https://gojs.net/latest/samples/sharedStates.html
