### ISSUE TITLE
DimensioningLink extension not binding points  

### ISSUE THREAD

**Issue by MrAbdelaziz** [NorthwoodsSoftware/GoJS#161]
Hi,

I found a bug in the DimensioningLink extension,
when you use it with binding points to save the current position after (reshapable edits ),

`                    $(DimensioningLink,{reshapable: true,resegmentable:true},
            new go.Binding("fromSpot", "fromSpot", go.Spot.parse),
            new go.Binding("toSpot", "toSpot", go.Spot.parse),
            new go.Binding("direction"),
            new go.Binding("extension"),
            new go.Binding("inset"),
`
now if I remove or add a new link with ( committing transitions ),
I lose the positions of links

**Comment by MrAbdelaziz** [comment]
the solution I found is adding
 `curve: go.Link.Link, adjusting: go.Link.Stretch`, I hope that helps someone else :)

**Comment by WalterNorthwoods** [comment]
That seems to be a bug in the DimensioningLink extension.  Try removing the call to updateTargetBindings() in the computePoints method.  I don't know why that call is there.
