### ISSUE TITLE
SVG output has unwanted shadows on text

### ISSUE THREAD

**Issue by YanikTheYak** [NorthwoodsSoftware/GoJS#163]
Issue : The latest version of GoJs – 2.1.54 is giving background shadows for text inside nodes for SVG output.
Note that this is not the case for PNGs.
We have observed this in the versions on or after 2.1.49. Where we see background  shadows for text inside nodes when outputting svg. However on the versions on or before 2.1.48 we do not have this issue.

Attached below is the sample html to verify the above usecase.
[svg.zip](https://github.com/NorthwoodsSoftware/GoJS/files/7650719/svg.zip)
You need to put gojs.js in a folder ../release/gojs.js

Below are the sample screenshots to get a glance.
On or before  2.1.48
![Before-gojs](https://user-images.githubusercontent.com/12268424/144632083-d525df85-cc16-4111-8f12-9a8224472ac0.png)

On or after 2.1.49
![after-gojs](https://user-images.githubusercontent.com/12268424/144632155-81dc0481-55bd-4eda-8fe3-e1a97d2ebb5a.png)

Thanks

**Comment by simonsarris** [comment]
Thank you for the reproducible case. We'll investigate and fix this soon.

**Comment by simonsarris** [comment]
This has been fixed, and will be out with the next release, probably early next week. I'll comment again and close this issue on release.

Thanks again.

**Comment by simonsarris** [comment]
We have just released 2.1.55 and the GoJS 2.2 Alpha, both of which contain the fix for this issue. Thanks again for reporting.

There is more information, here: https://forum.nwoods.com/t/gojs-version-2-2-alpha-and-gojs-2-1-55-released/15127
