### ISSUE TITLE
Images do not render in call to makeSvg or makeImage (Angular)

### ISSUE THREAD

**Issue by MrAbdelaziz** [NorthwoodsSoftware/GoJS#164]
Hello, 

makeSvg or makeImage  not serving pictures ,

the bug related to uppercase letters in the URL,

ref source: https://forum.nwoods.com/t/images-do-not-render-in-call-to-makesvg-or-makeimage/11669/32

**Comment by WalterNorthwoods** [comment]
Domain names are case insensitive.  URIs or URLs are generally case-sensitive.

**Comment by MrAbdelaziz** [comment]
i'm agree but something not working with the ng version
