### ISSUE TITLE
Animation not working when collapsing subgraph

### ISSUE THREAD

**Issue by ba2sik** [NorthwoodsSoftware/GoJS#167]
Hello,
If you look at [this demo](https://gojs.net/latest/samples/regrouping.html), when clicking + on `Main1`, the border/stroke around the items in the group, and the group header, is growing with animation, but when collapsing when clicking -, the stroke around the items and the header simply disappears, without doing it with animation.

Is it possible to override the closing animation somehow to make it work?

Thank you

**Comment by ba2sik** [comment]
?

**Comment by WalterNorthwoods** [comment]
Not easily.  It might be possible to turn off that built-in animation and implement everything yourself.

This is not a bug in the library or samples or documentation, so this topic does not belong here.

**Comment by ba2sik** [comment]
Why is this not a bug?
When expanding the group the border around the nodes is growing, and when collapsing the border disappears instead of shrinking.
This is inconsistent behavior in the library...

**Comment by WalterNorthwoods** [comment]
Yes, that does appear to be inconsistent.   However, that is how it was designed.  I suppose an implementation alternative could be achieved by customizing the group's border computation to include not-visible member nodes during animation.
