### ISSUE TITLE
Missing documentaion property

### ISSUE THREAD

**Issue by ba2sik** [NorthwoodsSoftware/GoJS#171]
At [`lineHeight`](https://gojs.net/latest/api/symbols/TextBlock.html#lineHeight) in TextBlock, it refers to the property `lineCount`, which does not exist.  
Instead, it says `{#lineCount}`, with no valid hash link. 

Does this property actually exist? (Sounds like a great way to deal with overflowed text, instead of the [old method](https://forum.nwoods.com/t/check-that-text-is-overflowed/9481/4)

**Comment by simonsarris** [comment]
Yes, it exists: https://gojs.net/latest/api/symbols/TextBlock.html#lineCount (actually, if you scroll up from `lineHeight`, you'll see it)

Both those properties have a typo in their docs. This will be fixed in the next release. Thank you.
