### ISSUE TITLE
when mouse hover the contextmenu,the textblock will disappear

### ISSUE THREAD

**Issue by ggunmo** [NorthwoodsSoftware/GoJS#173]
I add a textblock,a contextmenu in the diagram,when mouse hover the contextmenu(not click the button),the textblock will disappear,then I click other place,the textblock will appear again.
is it a gojs bug?or I write something wrong? help! 3q

![okwzd-3rekp](https://user-images.githubusercontent.com/18226120/169430382-d1ead8cc-cdb4-450e-8977-e43ccb0ae809.gif)

**Comment by WalterNorthwoods** [comment]
Please do not use the GitHub issue tracker unless you are reporting a bug in GoJS,
not a problem in your code nor a question about how to do something or use something.

For help and support, please use the GoJS forum: https://forum.nwoods.com/c/gojs
