### ISSUE TITLE
updateTargetBindings causing empty transactions in undoManager

### ISSUE THREAD

**Issue by lukeheckman** [NorthwoodsSoftware/GoJS#175]
[updateTargetBindings](https://gojs.net/latest/api/symbols/Model.html#updateTargetBindings) adds an empty step in the `undoManager` with an empty transaction name. Undoing or redoing will result in an extra step as well where no visual changes occur (e.g. Having to undo three times instead of two to revert a model's relinking steps).

![image](https://user-images.githubusercontent.com/70358560/171649458-0af3c0e6-ebc1-4eac-aa59-7aea0a724d15.png)

To fix this, I implemented a workaround using `skipsUndoManager` whenever calling `updateTargetBindings` to reach the intended behavior.

**Comment by WalterNorthwoods** [comment]
The operation of **updateTargetBindings** does not conduct a transaction.  It is just a way of evaluating some bindings.

Did you call **updateTargetBindings** within a transaction and without making any other changes to model or diagram that got recorded in the UndoManager?  You could do something like `myDiagram.commit(diag => {...}, null)` or `myDiagram.model.commit(m => {...}, null)` if you want to commit a transaction that skipsUndoManager.  A second argument of null conducts the whole transaction with **skipsUndoManager** set to false.
