### ISSUE TITLE
Ellipses/Rectangles drawing on edge of grid line, not center

### ISSUE THREAD

**Issue by interneth3ro** [NorthwoodsSoftware/GoJS#176]
When drawing a rectangle or ellipse onto a grid, the shape is rendered with the top border of the shape on the edge of the grid line. However, lines are rendered on top of the grid line, which results in the following:

![f16d85f7-0210-4dc7-b041-db934697e655](https://user-images.githubusercontent.com/5272022/172420807-2c2fb4ff-86ad-4031-a6c6-0afff3081e8b.png)

![71709e1d-26c8-4806-b68c-019321e2ec8f](https://user-images.githubusercontent.com/5272022/172420831-ae95668e-d9da-45ea-b6c1-943dd2f98b78.png)

I would like to be able to make the ellipse/rectangle sit on top of the grid line the same as the lines do. I will admit, I'm not sure if this is an actual bug with the GoJS software or not, but I'm just a contractor developer on a project using GoJS and don't really have the authority to create an account on the forums representing the company. But my Google-Fu has failed me in terms of looking for a solution. So I'll risk the wrath of creating something here that may not entirely be an issue. Thanks in advance.

**Comment by WalterNorthwoods** [comment]
Depending on how you defined the Parts, that behavior is quite plausible.

And you are right that it is not an issue with the library or extensions or samples or documentation, so your implied question really belongs in our forum.  Does your organization or client company not have a license and support contract?  Send us email.
