### ISSUE TITLE
Angular Sample: $digest already in progress

### ISSUE THREAD

**Issue by FritzHerbers** [NorthwoodsSoftware/GoJS#18]
Running https://gojs.net/latest/samples/angular.html in developer mode we get the below error in the console.
To reproduce: move one node and afterwards press "Replace Model" button.

We are evaluating GoJS at the moment and we use Toastr in our programs to display errors, also in production we will. We hope you can have a look into this issue and hopefully fix it soon.

"Error: [$rootScope:inprog] http://errors.angularjs.org/1.2.2/$rootScope/inprog?p0=%24digest
C/<@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.2/angular.min.js:6:449
f@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.2/angular.min.js:95:393
zd/this.$get</g.prototype.$apply@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.2/angular.min.js:101:300
.link/<@https://gojs.net/latest/samples/angular.html:78:13
E.prototype.Ba@https://gojs.net/latest/release/go.js:885:387
E.prototype.yw@https://gojs.net/latest/release/go.js:788:228
@https://gojs.net/latest/release/go.js:825:253
.link/<@https://gojs.net/latest/samples/angular.html:57:15
zd/this.$get</g.prototype.$digest@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.2/angular.min.js:99:139
zd/this.$get</g.prototype.$apply@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.2/angular.min.js:101:367
Mc[c]</<.compile/</<@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.2/angular.min.js:177:147
Yc/c/<@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.2/angular.min.js:27:13
q@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.2/angular.min.js:7:253
Yc/c@https://ajax.googleapis.com/ajax/libs/angularjs/1.2.2/angular.min.js:26:1
"

**Comment by WalterNorthwoods** [comment]
That's a flaw in the sample.  The problem is that replacing the **Diagram.model** may change the selection, which will result in a call to scope.$apply() at a time when that apparently is undesirable.

So change the "ChangedSelection" **DiagramEvent** listener to be:
```
          // update the model when the selection changes
          function updateSelection(e) {
            var selnode = diagram.selection.first();
            diagram.model.selectedNodeData = (selnode instanceof go.Node ? selnode.data : null);
            scope.$apply();
          }
          diagram.addDiagramListener("ChangedSelection", updateSelection);
```
and then make the model-watching listener smarter:
```
          // notice when the value of "model" changes: update the Diagram.model
          scope.$watch("model", function(newmodel) {
            var oldmodel = diagram.model;
            if (oldmodel !== newmodel) {
              diagram.removeDiagramListener("ChangedSelection", updateSelection);
              diagram.model = newmodel;
              diagram.addDiagramListener("ChangedSelection", updateSelection);
            }
          });
```
Alas it is too late for this change to go into the 1.6.5 release, which is partly released already.  When master has been updated here, I'll update the samples/angular.html file.
