### ISSUE TITLE
A bug in 2.2.12, when calling Diagram.makeSVG, link.geometry.figures might be null.

### ISSUE THREAD

**Issue by chelseachel** [NorthwoodsSoftware/GoJS#184]
It's a bug in GoJS 2.2.12.
When there is an orthogonal link in diagram, and the link have only two points, `link.geometry.figures` would be null.
And this causes an error in Diagram.makeSVG because link.geometry.figures is not iterable.

**Comment by WalterNorthwoods** [comment]
Thanks for reporting this bug.  It will be fixed in the 2.2.15 release, which should be coming out next week sometime.
