### ISSUE TITLE
Minimal sample diagram not visible

### ISSUE THREAD

**Issue by gertjandemulder** [NorthwoodsSoftware/GoJS#185]
The [README's minimal sample](https://github.com/NorthwoodsSoftware/GoJS#minimal-sample) diagram is not visible, probably because the size of `div` is not explicitly specified as instructed [here](https://gojs.net/latest/learn/#:~:text=Each%20GoJS%20diagram%20is%20contained%20in%20an%20HTML%20%3Cdiv%3E%20element%20in%20your%20HTML%20page%20that%20you%20give%20an%20explicit%20size%3A):

```html
<!-- The DIV for a Diagram needs an explicit size or else we will not see anything.
     In this case we also add a background color so we can see that area. -->
<div id="myDiagramDiv"
     style="width:400px; height:150px; background-color: #DAE4E4;"></div>
```

**Comment by simonsarris** [comment]
Whoops, thank you. We've just fixed this.
