### ISSUE TITLE
TypeError: a.forEach is not a function

### ISSUE THREAD

**Issue by gmsy** [NorthwoodsSoftware/GoJS#186]
Just installed gojs and gojs-react as described on the [official documentation](https://gojs.net/latest/intro/react.html),
However when I copy-pasted the code sample from that same page ("Rendering the component" section), I get a `TypeError: a.forEach is not a function` (as shown on screenshot).

How can I fix that?
Thanks.

![error](https://i.ibb.co/3SsDb46/gojs-error.png)

**Comment by simonsarris** [comment]
I'm not one of the resident react experts, but that page might be a little out of date compared to the [gojs-react-basic example](https://github.com/NorthwoodsSoftware/gojs-react-basic).

Still, when I pasted the code into a new project, changing it only a little, I did not come across this a.forEach issue. Did you add anything else?

**Comment by WalterNorthwoods** [comment]
It sounds as if you are not passing an Array as the diagram's model's nodeDataArray.

**Comment by gmsy** [comment]
Thank you guys for the replies.
For some reason the example on the [official documentation](https://gojs.net/latest/intro/react.html) gave me that error, but the [gojs-react-basic example](https://github.com/NorthwoodsSoftware/gojs-react-basic) did work. Thanks!
