### ISSUE TITLE
How to get Name Key onclick marker leaflet

### ISSUE THREAD

**Issue by exzant** [NorthwoodsSoftware/GoJS#189]
How to get **Name** Key when I click marker ?

![Screenshot - 14 Nov 2022 , 0_26_03](https://user-images.githubusercontent.com/31387785/201535339-e8937e6c-3eb5-43e7-9a06-a3798f792a57.png)

**Comment by simonsarris** [comment]
Please use the GoJS forum for support questions

https://forum.nwoods.com/c/gojs/11
