### ISSUE TITLE
Please provide the source code for the Data Flow (vertical) for the angular project

### ISSUE THREAD

**Issue by trinath-katari** [NorthwoodsSoftware/GoJS#192]
Please do not use the GitHub issue tracker unless you are reporting a bug in GoJS,
not a problem in your code nor a question about how to do something or use something.

For help and support, please use the GoJS forum: https://forum.nwoods.com/c/gojs

**Comment by WalterNorthwoods** [comment]
Sorry, but we do not have time to implement each sample in each version of every framework.
