### ISSUE TITLE
Extracting user data for graphs/flowcharts rendering

### ISSUE THREAD

**Issue by 87sam12** [NorthwoodsSoftware/GoJS#202]
Is there a way to extract user's input for rendering the diagrams:

Lets suppose I have a UI like below, can I easily get inputs from user within those boxes? as most of the docs I see seem to render existing data

![image](https://github.com/NorthwoodsSoftware/GoJS/assets/13358855/f00ffc73-db55-4c74-9f69-80406d2ac556)

I dint refer the docs much. But from whatever I saw the apis allow data to be rendered when feeded as json. But not sure whether those shapes allow data to be entered by users.

**Comment by simonsarris** [comment]
Yes you can set any of the `TextBlock`'s `.editable` to `true` to allow user input.

Please use the [forum](https://forum.nwoods.com) for support requests.
