### ISSUE TITLE
Module not found error for go-debug

### ISSUE THREAD

**Issue by RaemyS** [NorthwoodsSoftware/GoJS#207]
Hi,

We have tried to update gojs from version 2.**2**.16 to 2.**3**.16. The following error message now appears during the build:

Module not found: Error: Package path ./release/go-debug is not exported from package C:\...\node_modules\gojs (see exports field in C:\...\node_modules\gojs\package.json)

We import it as follows:
import * as go from 'gojs/release/go-debug';

The library is used in a project with Angular 17.

We could not find any indications in the changelog that we need to make adjustments to the imports.

Could this be a bug?

Thanks in advance for your help

**Comment by RaemyS** [comment]
Ok, thanks for your quick reaction. I will downgrade and try again with 2.3.17. Could you mention here when the new version is ready?

**Comment by simonsarris** [comment]
We'll probably be releasing later today (2.3.17 also contains some SVG renderer fixes), but I won't close this issue until 2.3.17 is out.

**Comment by simonsarris** [comment]
2.3.17 has been released, please give it a try and let us know if it fixes your issue.

**Comment by RaemyS** [comment]
2.3.17 is now installed and the build works fine now. Thanks for your quick fix👍
