### ISSUE TITLE
Copying nodes in version 3.0.0 does not work

### ISSUE THREAD

**Issue by Flareonn** [NorthwoodsSoftware/GoJS#209]
You can compare it to the 2.3 version. Bug on version 3.0.0

All because of the announced change of InputEvent.key. Copying doesn't work on Russian layout exactly, I can't speak for others. It is reproduced only on Windows systems.

Why? I noticed that on Mac, when you click cmd, your .key ignores the keyboard layout and is always specified with an English letter, but not so on Windows

At the moment you can fix this behavior yourself with this code

```typescript
    const isMac = navigator.platform.toUpperCase().indexOf('MAC')>=0;

    class CustomCommandHandler extends go.CommandHandler {
      public override doKeyDown(): void {
        const event = this.diagram.lastInput.event

        if(event instanceof KeyboardEvent) {
          const isCtrlPressed = isMac ? event.metaKey : event.ctrlKey
          if(isCtrlPressed) {
            if(event.code === 'KeyC' && this.canCopySelection()) {
              this.copySelection()
  
              return 
            }
  
            if(event.code === 'KeyV' && this.canPasteSelection()) {
              this.pasteSelection()
  
              return
            }
          }
        }

        return super.doKeyDown()
      }
    }
 
```
 
After that, use it when initializing go.Diagram

**Comment by simonsarris** [comment]
Reading about this now, I see the error. We'll make this more durable in 3.0.1

Out of curiosity, what are the Russian keys for copy and paste shortcuts? Are they just physically where C and V are on QWERTY style layouts?

**Comment by Flareonn** [comment]
> Reading about this now, I see the error. We'll make this more durable in 3.0.1
> 
> Out of curiosity, what are the Russian keys for copy and paste shortcuts? Are they just physically where C and V are on QWERTY style layouts? In other words the .key values are `ц` and `в` instead, presumably?

The keys are the same, just in their place:  `с` for C and `м` for V.

![image](https://github.com/NorthwoodsSoftware/GoJS/assets/35931685/7cd7dd5a-0bf4-45ab-8b69-e4176d26aced)

**Comment by simonsarris** [comment]
if you try: https://gojs.net/temp/go301a.js

Does it work as you'd expect?

Live example: https://codepen.io/simonsarris/pen/OJGdZox?editors=1011

**Comment by Flareonn** [comment]
> if you try: https://gojs.net/temp/go301a.js
> 
> Does it work as you'd expect?
> 
> Live example: https://codepen.io/simonsarris/pen/OJGdZox?editors=1011

Yes

**Comment by simonsarris** [comment]
Ok, we'll release 3.0.1 in the coming days which will include this fix. Thank you for your help. I will close this issue when its released.

**Comment by simonsarris** [comment]
3.0.1 has been released and should fix this. Thank you for your help.
