### ISSUE TITLE
GoJS 3.0.3 and AvoidsLinksRouter.js

### ISSUE THREAD

**Issue by LuckyTil** [NorthwoodsSoftware/GoJS#214]
AvoidsLinksRouter.js plugin uses call to "positions.maxUnoccupiedV" and "positions.maxUnoccupiedH" methods.
But GoJS 3.0.3 not contains that methods.

**Comment by simonsarris** [comment]
Sorry, those undocumented properties were renamed `maxAvoidsLinksSpaceV` and `maxAvoidsLinksSpaceH` to make their purpose somewhat more clear. But while we changed the TS source file, we forgot to transpile before releasing so [this file](https://gojs.net/latest/extensions/AvoidsLinksRouter.js) used in the [avoids links sample](https://gojs.net/latest/samples/AvoidsLinksRouter.html) was incorrect. That has been fixed.

**Comment by LuckyTil** [comment]
@simonsarris ,
Thanx!
