### ISSUE TITLE
Initial opening limit and expander limit

### ISSUE THREAD

**Issue by muhammedfisek** [NorthwoodsSoftware/GoJS#218]
Hello,

The entire tree is displayed openly at startup. I have 2 requests.

1. Only the first 10 rows should be loaded at startup.
2. Each time the expander is pressed, the 3 lower rows should be loaded.

How can I do these?

**Comment by WalterNorthwoods** [comment]
This is not reporting an issue with the library, but is a question asking about how to use the library.  Those questions belong in the forum https://forum.nwoods.com/c/gojs/11/l/latest

If you do post there, you'll want to provide more information, including some screenshots or sketches, showing what you have now and what you want instead.
