### ISSUE TITLE
line-height is not ok

### ISSUE THREAD

**Issue by hstarorg** [NorthwoodsSoftware/GoJS#22]
Can not view whole word in TextBlock.
Demo URL: http://gojs.net/latest/samples/selectableFields.html

**Comment by simonsarris** [comment]
This looks fine to me, so I'm going to need more detail.

<img width="289" alt="capture" src="https://cloud.githubusercontent.com/assets/340971/15114349/886d3f74-15c7-11e6-995f-e58362505b5e.PNG">

**Comment by simonsarris** [comment]
Closing this as not library-bug-related. If you need help, you can use the [forum](https://forum.nwoods.com/c/gojs).

**Comment by hstarorg** [comment]
@simonsarris In my browser,is this: 
![qq 20160510001446](https://cloud.githubusercontent.com/assets/4043284/15119645/6fc82600-1644-11e6-9514-d627c27888bf.png).
My browser is : Chrome 48.0.2564.109 m

**Comment by simonsarris** [comment]
It looks like your browsers or system's default font is not a sans-serif font, as specified in the sample, but a monospace serif font. I do not know why this is, but I suspect its an issue with HTML canvas rendering and measuring that particular font.

**Comment by hstarorg** [comment]
I think so, but I have no solution to resolve it.
