### ISSUE TITLE
Diagram context menu not opening on long-press in Edge (Microsoft Surface 4 Pro)

### ISSUE THREAD

**Issue by dominicdesu** [NorthwoodsSoftware/GoJS#25]
Hello,

I opened the [goJS basic sample page](http://gojs.net/latest/samples/basic.html) in Edge browser on a Microsoft Surface 4 Pro.
According to the description, holding the finger stationary should bring up a context menu. However, this is not happening. I can see the square which is usually displayed when a long-press is performed, but no context menu is displayed. Doing the same in Chrome on the Surface 4 works just fine.

Any idea or more information which I could provide?

Best regards,
Dominic

**Comment by simonsarris** [comment]
We'll investigate.

**Comment by simonsarris** [comment]
I _think_ this will be fixed in the next release. If you want to help with testing, you can email us, gojs (at) nwoods.com, and I'll send you a provisional version of the library.

**Comment by simonsarris** [comment]
This has been fixed in 1.6.11 (to be released soon)

Thanks for reporting this @dominicdesu

**Comment by dominicdesu** [comment]
Hi @simonsarris,
thanks for fixing this issue, it works fine now on the Surface using finger gestures.

When playing around with the Surface Pen, though, I realized that I cannot access the context-menu. I assume the Surface is sending a different event when long-pressing with the pen compared to long-pressing with a finger. As the pen has no right-click, I don't know how else to open the conext menu using the pen. Is this something which can be "fixed" in goJS or do I need to find a seperate solution?
