### ISSUE TITLE
Typescript compile error: "... node_modules/gojs/release/go.d.ts' is not a module"

### ISSUE THREAD

**Issue by KostyaDanovsky** [NorthwoodsSoftware/GoJS#26]
I use Typescript 1.8 but to fix this issue I need to change following lines in go.d.ts file:

```
declare module "go" {  
  export = go;         
}
```
to
`export = go;`

**Comment by WalterNorthwoods** [comment]
I'm using TypeScript 1.8.35, and when the go.d.ts file includes, at the end of the file:
```
// for TypeScript 1.*:
declare module "go" {  // comment out module declaration for TypeScript 2.0
  export = go;         // but keep export = go in all versions for compatibility with AMD and CommonJS
}
```
I do not get an error when compiling the following code:
```
    var $ = go.GraphObject.make;  // for conciseness in defining templates

    var myDiagram: go.Diagram =
        $(go.Diagram, "myDiagram",  // create a Diagram for the DIV HTML element
            {
                // position the graph in the middle of the diagram
                initialContentAlignment: go.Spot.Center
            });
```

So could you explain why you think there should not be a "go" module declaration in the go.d.ts file?

**Comment by herecydev** [comment]
I'm seeing the same problem. The `package.json` looks fine, both main and typings are pointing to the correct files. The typescript compiler throws the following: `error TS2306: File 'C:/snipped/node_modules/gojs/release/go.d.ts' is not a module.` The fix suggested at the top does work. The problem I have with the whole thing is that this is not a sustainable practice. I can't comment this code out during CI deployment or on another developer's machine. Can you please take another look at this problem.

<details>
Typescript 1.8.10. 
GoJs 1.6.15. 
Node v4.4.7.
</details>
``

**Comment by WalterNorthwoods** [comment]
Which fix "suggested at the top" are you talking about?

        ---Walter

**Comment by herecydev** [comment]
> I need to change following lines in go.d.ts file:
>
> declare module "go" {  
>  export = go;         
> }
> to
> export = go;

**Comment by WalterNorthwoods** [comment]
How are you importing GoJS in your TypeScript code?

Later today I can experiment how such a change would work in AMD
environments, although I thought it did not.

Unless you wish to keep your email address private, could you just send
email to GoJS@nwoods.com?

        ---Walter

**Comment by herecydev** [comment]
With ES6 syntax; `import * as go from "gojs"`

**Comment by WalterNorthwoods** [comment]
OK, I still cannot reproduce that TSC error, and that error you quoted does not make sense anyway.  And a lot of other TypeScript definition files wrap their `export = blah` with a `declare module "blah" { }`.

But it does seem to work without that module declaration, so I'll change it for 1.6.17.
