### ISSUE TITLE
Support modules for tree shaking

### ISSUE THREAD

**Issue by herecydev** [NorthwoodsSoftware/GoJS#29]
Are there any plans for using ES6 modules, so that tools like webpack/rollup.js can tree shake? I'm worried about the size of the library, and ideally only want to package up the sections I'm using.

**Comment by WalterNorthwoods** [comment]
Not yet, but I would expect any competent dead code elimination mechanism to recognize classes that are not used and remove them.  The Closure compiler does this, for example -- no need to require ES6 and modules.

**Comment by simonsarris** [comment]
Future versions of GoJS will use modules, but we do not have a concrete timetable for the release.
