### ISSUE TITLE
Problem with nodeIsGroupProperty and Palette

### ISSUE THREAD

**Issue by Chali-Anne** [NorthwoodsSoftware/GoJS#30]
Hi,

I have a diagram and a palette that both share the same nodeTemplateMap and groupTemplateMap. My objects do not have a property _isGroup_, and I would highly prefer it if it could stay that way. The problem is, when I go and set nodeIsGroupProperty with a function on the GraphLinksModel, the groups are displayed properly on the diagram but the Palette contains **-1, -2** and outputs 

> No NodeTemplate found for category **_name of group category_**.

This tells me that the Palette could not tell my element was a group. How could I make the Palette display groups like the ones in the diagram?

**Comment by WalterNorthwoods** [comment]
Shouldn't you be setting **GraphLinksModel.nodeIsGroupProperty** to a function on your **Palette** as well as your main **Diagram**?

We'd prefer if you ask questions on our forum, https://forum.nwoods.com/c/gojs.

**Comment by Chali-Anne** [comment]
Hi,

I set it on the Palette's model with a cast and now it displays groups properly.

Thank you!
