### ISSUE TITLE
Integrate GoJS in mobile (Native)

### ISSUE THREAD

**Issue by yhelfronda** [NorthwoodsSoftware/GoJS#31]
Hello,

Can it be used in mobile platforms like iOS and Android? Because we are going to build mobile app with this kind of feature like  [this one](https://play.google.com/store/apps/details?id=com.plangrid.android). 

Thank you.

**Comment by WalterNorthwoods** [comment]
Yes.

GitHub issues are meant for reporting problems, not asking questions. I suggest that you search the forum and ask questions there. https://forum.nwoods.com/c/gojs
