### ISSUE TITLE
angular2 minimal project

### ISSUE THREAD

**Issue by mwaaas** [NorthwoodsSoftware/GoJS#33]
Have just followed instructions on angular2 minimal project and am getting the following error. 
<img width="689" alt="screen shot 2017-03-13 at 8 20 21 am" src="https://cloud.githubusercontent.com/assets/6207932/23842475/85fac57c-07c5-11e7-921d-f2a3e2ea1216.png">

**Comment by WalterNorthwoods** [comment]
Sorry about that -- I forgot to include the subdirectories in that project.  I have checked them in, but I'm not going to try to modify the release -- that will have to wait until 1.7.4.
