### ISSUE TITLE
Can this be used in React?

### ISSUE THREAD

**Issue by fgiarritiello** [NorthwoodsSoftware/GoJS#34]
Can this be used in react? If so, is there a guide? Thanks in advanced

**Comment by WalterNorthwoods** [comment]
A web search finds:

https://gist.github.com/michaelryancaputo/f11ec3db2c8aa3158f702f27472608ff
http://stackoverflow.com/questions/40451705/using-gojs-in-reactjs
https://forum.nwoods.com/t/using-gojs-with-reactjs-and-redux/8015

Usage questions are not issues that should be entered here -- they can be asked in the forum, https://forum.nwoods.com/c/gojs, or by email, https://www.nwoods.com/contact.html.
