### ISSUE TITLE
Request for using GoJS in sky-walking open source apm.

### ISSUE THREAD

**Issue by wu-sheng** [NorthwoodsSoftware/GoJS#35]
Hi, I am the founder and developer of [sky-walking apm](https://github.com/wu-sheng/sky-walking). In its 3.0 version, we will provide a topological graph about a distributed application cluster. Also as a core member of [OpenTracing](http://opentracing.io), inferring applications  topological graph is a very important feature.

Right now, I can do this:
![wechatimg32](https://cloud.githubusercontent.com/assets/5441976/24588193/3104d832-17f6-11e7-88d2-782b28babdc7.jpeg)

I have tried to use `GoJS` to do the topological graph, it works better. Although `GoJS` is open source, it has a license restriction.

I want you to approve us using `GoJS` in `sky-walking apm`. Hope you can help our open source team.

**Comment by simonsarris** [comment]
You may include the evaluation version of GoJS in open source projects, but people who use your project and want to use GoJS with it will have to purchase a license.

Since this is not a bug or code issue, please email us (gojs @ nwoods.com) instead of using the issue tracker.

**Comment by wu-sheng** [comment]
Just send the mail. Have some questions about license things.
