### ISSUE TITLE
Diagram context menu not opening on long-press with Pen (Microsoft Surface 4 Pro)

### ISSUE THREAD

**Issue by dominic-simplan** [NorthwoodsSoftware/GoJS#38]
Hello,

I opened the goJS basic sample page on a Microsoft Surface 4 Pro (Edge, Chrome). However, it is not possible to open the context menu using the **surface pen**. I can see a circle which is usually displayed when a long-press is performed, but no context menu is displayed.
Opening the context menu using a finger instead (long-touch) works as expected. (Also see #25).

Any idea or more information I could provide?

Best regards,
Dominic

**Comment by WalterNorthwoods** [comment]
We can add such a feature, at least on Edge.  We'll look into it.

**Comment by WalterNorthwoods** [comment]
I believe this now works in version 1.8.3.
