### ISSUE TITLE
latest release 1.7.11 - release directory d.ts files not properly installing

### ISSUE THREAD

**Issue by kgentes** [NorthwoodsSoftware/GoJS#40]
**OS**: Windows 7 SP1
**Node**: 7.10.0
**GoJS**: 1.7.11 (latest)

The latest release looks like it includes a Typescript definition file for the `go-debug.js` library. Thank you!

Strangely, however, the file does not actually installed when using the `npm install` command on the latest package.  I verified that this file exists on your repo. Then I checked to see the results of the `npm install`, and noted that the `go-debug.d.ts` file is not actually installed in the `node_modules/gojs/release` directory. See attached screen shot as well.

![release-listing](https://cloud.githubusercontent.com/assets/5266827/26362210/20f1cec8-3f92-11e7-902d-d04c914ca777.png)

You can confirm this behavior by doing an `npm install` as well.

**Comment by simonsarris** [comment]
That's weird. Are you sure you have installed the latest version with NPM? We just published less than an hour ago.

**Comment by WalterNorthwoods** [comment]
Ah, that's because I didn't update the `package.json` file, which for some reason has an explicit list of files to include.  I cannot re-release 1.7.11 in npm, so this will have to wait until the next release.  Sorry about that.
