### ISSUE TITLE
 the Diagram in hidden tabitem is not work

### ISSUE THREAD

**Issue by lifanmvc** [NorthwoodsSoftware/GoJS#43]
Hi:
    When I use gojs，it's very good.but when I use bootsrap's tab, I find as question: the Diagram in hidden tabitem is not work.
code :
<ul id="configTab" class="nav nav-tabs">
    <li>
        <a href="#myDiagramDiv" data-toggle="tab">workfow</a>
    </li>
    <li>
        <a href="#testLk" data-toggle="tab">other</a>
    </li>
</ul>
<div id="configTabContent" class="tab-content">
    <div class="tab-pane fade" id="myDiagramDiv"
         style="width:100%; height:180px; background-color: #DAE4E4;"></div>
    <div class="tab-pane fade" id="testLk"
         style="width:100%; height:180px; background-color: red;"></div>
</div>
<hr />
<ul id="configTab1" class="nav nav-tabs">
    <li>
        <a href="#testLk1" data-toggle="tab">other</a>
    </li>
    <li>
        <a href="#myDiagramDiv1" data-toggle="tab">workfow</a>
    </li>
</ul>
<div id="configTabContent" class="tab-content">
    <div class="tab-pane fade" id="testLk1"
         style="width:100%; height:180px; background-color: red;"></div>
    <div class="tab-pane fade" id="myDiagramDiv1"
         style="width:100%; height:180px; background-color: #DAE4E4;"></div>
</div>
        <script type="text/javascript">
            //var diagram;
            $(document).ready(function () {
                fn_LoadWokflowDiagram();
                $('#configTab li:eq(0) a').tab('show');
                $('#configTab1 li:eq(0) a').tab('show');
            });

            function fn_LoadWokflowDiagram() {

                var myDiagram = new go.Diagram("myDiagramDiv");
                myDiagram.model = new go.GraphLinksModel(
                    [{ key: "Hello" },   // two node data, in an Array
                    { key: "World!" }],
                    [{ from: "Hello", to: "World!" }]  // one link, in an Array
                );

                var myDiagram1 = new go.Diagram("myDiagramDiv1");
                myDiagram1.model = new go.GraphLinksModel(
                    [{ key: "Hello" },   // two node data, in an Array
                    { key: "World!" }],
                    [{ from: "Hello", to: "World!" }]  // one link, in an Array
                );
            }
        </script>
please help,thank you

**Comment by WalterNorthwoods** [comment]
Does this help: http://gojs.net/latest/intro/resizing.html ?

**Comment by lifanmvc** [comment]
It's work,thanks you very much.

发自我的 iPad
