### ISSUE TITLE
is there a plan to support vue :)

### ISSUE THREAD

**Issue by GodFaker** [NorthwoodsSoftware/GoJS#44]
vue is very popular now ,and i am using it to ,so can you support vue or add a example like angular?:)

**Comment by WalterNorthwoods** [comment]
I suppose we could learn enough about Vue.js to be able to create a sample.

But you must be using it now, yes?  What problems have you encountered?

**Comment by WalterNorthwoods** [comment]
https://gojs.net/latest/samples/vue.html

**Comment by GodFaker** [comment]
yeah ,i just make a suggestion ,because i find that there is a example for ng in the sample folder。if there is a simple demo for vue, it can give a direct guide for vuer that the product can work fine with vue。anyway, i am happy for you add a example:)haha
