### ISSUE TITLE
“setDataProperty” cannot be called forever

### ISSUE THREAD

**Issue by pingwei-sun** [NorthwoodsSoftware/GoJS#45]
A permanent call will cause a browser crash（jsheap rise）

**Comment by WalterNorthwoods** [comment]
If you have enabled the **UndoManager**, then of course it will record the change in a **ChangedEvent**, which does take some memory. This is required if the change wants to be undone.

If you don't want the change to be recorded, remember the value of **Model.skipsUndoManager**, temporarily set **Model.skipsUndoManager** to true, do your change(s), and then restore **Model.skipsUndoManager** to its original value.

**Comment by pingwei-sun** [comment]
Improper use，Exceed the maxHistoryLength
