### ISSUE TITLE
Bug in HTML

### ISSUE THREAD

**Issue by vorant** [NorthwoodsSoftware/GoJS#47]
Code example is too small and is on the right side.
Chrome v. 63.0.3239.84 Win10.

Also Github link isn't work.

https://gojs.net/latest/samples/twodiagrams.html
![image](https://user-images.githubusercontent.com/4313099/34339954-e0425be2-e9ad-11e7-8dda-17ae21aa0f49.png)

**Comment by WalterNorthwoods** [comment]
Thanks for reporting the non-optimal HTML in that sample.  Here's what will be in 1.8.7, which will be released within a week or so.

    <div style="width: 100%; display: flex; flex-wrap: wrap">
      <div>
        <div id="myDiagramDiv" style="border: solid 1px black; width:350px; height:300px; margin: 0 2px 0 0"></div>
        <p>
          <label><input type="checkbox" onclick="allChecks()" id="MD1allowDragOut" />allowDragOut</label>
          <label><input type="checkbox" onclick="allChecks()" id="MD1allowDrop" />allowDrop</label>
          <label><input type="checkbox" onclick="allChecks()" id="MD1isReadOnly" />isReadOnly</label>
        </p>
        <p>
          <label><input type="checkbox" onclick="allChecks()" id="MD1allowCopy" />allowCopy</label>
          <label><input type="checkbox" onclick="allChecks()" id="MD1allowDelete" />allowDelete</label>
          <label><input type="checkbox" onclick="allChecks()" id="MD1allowInsert" />allowInsert</label>
          <label><input type="checkbox" onclick="allChecks()" id="MD1allowMove" />allowMove</label>
        </p>
      </div>
      <div>
        <div id="myDiagram2" style="border: solid 1px black; width:350px; height:300px"></div>
        <p>
          <label><input type="checkbox" onclick="allChecks()" id="MD2allowDragOut" />allowDragOut</label>
          <label><input type="checkbox" onclick="allChecks()" id="MD2allowDrop" />allowDrop</label>
          <label><input type="checkbox" onclick="allChecks()" id="MD2isReadOnly" />isReadOnly</label>
        </p>
        <p>
          <label><input type="checkbox" onclick="allChecks()" id="MD2allowCopy" />allowCopy</label>
          <label><input type="checkbox" onclick="allChecks()" id="MD2allowDelete" />allowDelete</label>
          <label><input type="checkbox" onclick="allChecks()" id="MD2allowInsert" />allowInsert</label>
          <label><input type="checkbox" onclick="allChecks()" id="MD2allowMove" />allowMove</label>
        </p>
      </div>
    </div>
    <div>
      Using the Robot extension class:<br />
      <button onclick="dragBetaAcross()">Drag Beta across</button><br />
      <button onclick="copyBetaBack()">Copy Beta back</button>
    </div>
