### ISSUE TITLE
API Documentation default values.

### ISSUE THREAD

**Issue by ertant** [NorthwoodsSoftware/GoJS#5]
Most of API documentation lack of default values of class properties. An example; what is the default value of GridLayout.arrangement property if not specified ? Otherwise it's hard to understand why and how it behaves.

As a suggestion you may include an additional column in properties table to put default value.

**Comment by simonsarris** [comment]
Wait, where are you looking?

For instance here: http://gojs.net/latest/api/symbols/GridLayout.html

It says "The default value is GridLayout.LeftToRight."

**Comment by ertant** [comment]
Ah ok, sorry i think my downloaded copy is older. Thanks for very fast reply.
