### ISSUE TITLE
OrthogonalLinkReshapingTool with Angular2 Error

### ISSUE THREAD

**Issue by nephilimboy** [NorthwoodsSoftware/GoJS#50]
Hi, 
Thanks for great library,,,, i want to run OrthogonalLinkReshaping example on **angular 2**, i've already tested the gojs angular sample example, and it work perfectly, after that i add OrthogonalLinkReshapingTool.js to my .angular-cli.json and add OrthogonalLinkReshapingTool sample code to my app.component.ts. here is my app.component.ts file
```
import { Component, OnInit, ViewChild, ElementRef, AfterContentInit } from '@angular/core';
import * as go from 'gojs';
declare var OrthogonalLinkReshapingTool;
@Component({
  selector: 'app-home',
  template: `
  <div id="myDiagramDiv" #myDiagramDiv style="border: solid 1px black; width:100%; height:600px"></div>
  `,
})
export class HomeComponent implements OnInit, AfterContentInit {

  @ViewChild('myDiagramDiv') myDiagramDiv: ElementRef

  public myDiagram: any;
  constructor(private element: ElementRef) {
  }
  ngOnInit() {
  }
  ngAfterContentInit() {
    let $ = go.GraphObject.make;
    console.log($);
    this.myDiagram = $(go.Diagram, this.myDiagramDiv.nativeElement,({
        "initialContentAlignment": go.Spot.Center,
        "undoManager.isEnabled": true,
        "linkReshapingTool": new OrthogonalLinkReshapingTool()
    }));
    // Rest OF the Code from GOJS OrthogonalLinkReshaping.html sample
  }
   
}
```
when i run this code i got this error:
```
ERROR Error: ToolManager.replaceStandardTool:newtool value is not an instance of Tool: OrthogonalLinkReshaping Tool
    at Object.k (go.js:14)
    at Object.Dd (go.js:15)
    at Object.G (go.js:14)
    at Dk (go.js:688)
    at ih.eval (go.js:691)
    at Object.Su (go.js:27)
    at dp (go.js:1094)
    at bp (go.js:1089)
    at HomeComponent.ngAfterContentInit (home.component.ts:30)
    at callProviderLifecycles (core.js:12423)
```
I've seen some error like this from this post : 
`https://forum.nwoods.com/t/presales-question-draggable-link-error/7564`
but mine is different coz i used **OrthogonalLinkReshapingTool.js** file. so how can i solve this?
thanks in advance

**Comment by WalterNorthwoods** [comment]
How are you loading the `OrthogonalLinkReshapingTool.js` code?  I suggest that you `import` it from `....extensionsTS/OrthogonalLinkReshapingTool`.

**Comment by nephilimboy** [comment]
thanks for reply
it solve now,, i used extensionsTS/OrthogonalLinkReshapingTool.ts instead of extensions/OrthogonalLinkReshapingTool.js file, but why the js file doesn’t work with typescript?
i added that js file in my script section on .angular-cli.json like this 
```
"./assets/OrthogonalLinkReshapingTool.js" 
```
and it doesn’t work. even if i add it in my index.html (**<script src="assets/OrthogonalLinkReshapingTool.js"></script>**) it doesn’t  work either. only if i use the TS version, it work properly. i know the TS files convert to js file at the end so it shouldn't  problem if i use js file or ts file as library, so why it matter in this case?

**Comment by WalterNorthwoods** [comment]
`extensions/*.js` are scripts; `extensionsTS/*.js` are UMD modules.
