### ISSUE TITLE
how to start this project??

### ISSUE THREAD

**Issue by juuuuuuuuuuuuuu** [NorthwoodsSoftware/GoJS#56]
Please do not use the GitHub issue tracker, unless you are reporting a potential bug.

For help and support, please use the GoJS forum: https://forum.nwoods.com/c/gojs

how to start this project?
npm install --> npm start is not working....

**Comment by WalterNorthwoods** [comment]
Please do not use the GitHub issue tracker, unless you are reporting a potential bug.

For help and support, please use the GoJS forum: https://forum.nwoods.com/c/gojs
