### ISSUE TITLE
Create workflows useing gojs.

### ISSUE THREAD

**Issue by 426-330** [NorthwoodsSoftware/GoJS#57]
![image](https://user-images.githubusercontent.com/2107423/38246185-84dfff34-3773-11e8-86de-c489c98e78f8.png)

Hi,here are some uncontrollable problem.
I'm binding location for the nodes.
The lines are unaligned,and the under is ok.

**Comment by WalterNorthwoods** [comment]
Please do not use the GitHub issue tracker, unless you are reporting a potential bug.  For help and support, please use the GoJS forum: https://forum.nwoods.com/c/gojs

The locations of the nodes are correct, are they not?  The normal routes that links would take are just like those that you show in the lower diagram.  What values are you using for **fromSpot** and **toSpot**?  What properties have you set on the **Link**s?  Chances are that you have specified some properties unnecessarily.
