### ISSUE TITLE
Can't use myDiagram.model.removeLinkData to delete a line

### ISSUE THREAD

**Issue by XiaoxinJiang** [NorthwoodsSoftware/GoJS#59]
I can use myDiagram.model.addLinkData({from: "sync_sql", to: "testb"}) to add a line. but when I use 
myDiagram.model.removeLinkData({from: "sync_sql", to: "testb"}), It can't be deleted.

**Comment by WalterNorthwoods** [comment]
You need to pass a specific link data object reference to **GraphLinksModel.removeLinkData**: https://gojs.net/latest/api/symbols/GraphLinksModel.html#removeLinkData

You cannot create a new object and expect to find a similar object that is a link data object.

**Comment by XiaoxinJiang** [comment]
Thank you very much.I try it
