### ISSUE TITLE
Problem with GoJS and bootstrap

### ISSUE THREAD

**Issue by iivanov2** [NorthwoodsSoftware/GoJS#6]
There is a problem with GoJS library, if I use twitter's bootstrap in the same time.
Scrollbars of the stage are dislocated if diagram is bigger than the div container.
Some screen caputres of Internet Explorer 9 (similar problem in Chrome too).

With bootstrap (http://getbootstrap.com/):
![capture-with-bootstrap](https://cloud.githubusercontent.com/assets/9646935/5805306/504157d4-a016-11e4-821f-99e5e8b0a7ab.PNG)

Without bootstrap:
![capture-without-bootstrap](https://cloud.githubusercontent.com/assets/9646935/5805313/65ab0160-a016-11e4-9014-f9b8a4c7dcb7.PNG)

**Comment by simonsarris** [comment]
Is this still an issue? Have you tried a CSS reset of divs and the canvas inside of the #myDiagram ID'd element?

**Comment by iivanov2** [comment]
Hi,there is no such thing as CSS reset you can't isolate an div or other tag as you think. I sloved my problem as I embed the diagram in an iframe, in this  way it has separate CSS rules, without bootstrap.I see that you released a new version 1.4.22 (I am still using 1.4.19) but it has still this bug, I send you  new images here:http://s14.postimg.org/t9b2c62u9/Capture1.pnghttp://s1.postimg.org/nl2ocoqlr/Capture2.pnghttp://s29.postimg.org/3ro5ppahj/Capture3.png     I repeat, this problem occurs most visible in IE9 when I am using bootsrap, and there is similar problem with other browsers (Chrome, Firefox).

**Comment by simonsarris** [comment]
I mean you could find the rules that are modifying the Diagram div or its canvas and reset them to defaults, e.g.:

#myDiagram canvas {
  /* modify all canvases inside of myDiagram ID, reversing whatever Bootstrap rule is breaking GoJS */
}

**Comment by iivanov2** [comment]
I understand now but I didn't try this it was easier for me to embed it in iframe.

**Comment by simonsarris** [comment]
Okay, closing the issue then. Thanks for reporting.
