### ISSUE TITLE
Genogram Layout node location issue

### ISSUE THREAD

**Issue by njwest** [NorthwoodsSoftware/GoJS#61]
We are customizing [this GoJS Genogram code](https://gojs.net/latest/samples/genogram.html)

Can we input parameters to render the nodes within the Genogram to certain locations? 

Is there a simple way to customize the node locations on the Genogram layout?

The genogram layout appears to be overriding our custom node locations upon rendering

```
layout:  // use a custom layout, defined below
              $(GenogramLayout, { direction: 90, layerSpacing: 30, columnSpacing: 10})
```

**Comment by WalterNorthwoods** [comment]
Please do not use the GitHub issue tracker, unless you are reporting a potential bug.

For help and support, please use the GoJS forum: https://forum.nwoods.com/c/gojs

You might want to set **Layout.isInitial** to false, to prevent the **GenogramLayout** from running when you load a model.

**Comment by njwest** [comment]
Duly noted, thanks!
