### ISSUE TITLE
Do you support server side rendering？

### ISSUE THREAD

**Issue by milu2003** [NorthwoodsSoftware/GoJS#62]
For example, on nuxt(https://nuxtjs.org/guide/views/), using server rendering to speed up page opening speed.

**Comment by simonsarris** [comment]
We allow server side rendering, but do not automatically render server side and serve to client.

https://gojs.net/latest/intro/serverSideImages.html

Please do not use the issue tracker for questions, use the [forum](https://forum.nwoods.com/c/gojs) instead.
