### ISSUE TITLE
Problem in updateAllTargetBindings() and palette

### ISSUE THREAD

**Issue by kiwing1994** [NorthwoodsSoftware/GoJS#66]
Drop node from palette to diagram (Force-Directed Layout)
then call diagram.updateAllTargetBindings()
node from palette will move to center (0,0) and display vertically using order in palette
node from difference palette overlap

gojs: 1.8.28

**Comment by WalterNorthwoods** [comment]
If your node template has a OneWay Binding on **Node.location**, I could see how that could happen.  That would not be a bug in the library, but in you define and use your node template and in what data you have in the model.

If you don't need a binding on **Node.location**, remove it and the corresponding source property on the node data objects.

If you do need a binding on **Node.location** despite the **Diagram.layout** being a **ForceDirectedLayout**, then make it a TwoWay Binding.
