### ISSUE TITLE
More description in readme

### ISSUE THREAD

**Issue by RonjaKnudtsen** [NorthwoodsSoftware/GoJS#68]
The readme here describes how to setup Angular. 
But an Angular developer already knows this. Could you give some details about setting up the dependencies for GoJS?

**Comment by simonsarris** [comment]
There are no GoJS dependencies. Have you seen: https://github.com/NorthwoodsSoftware/GoJS-projects/tree/master/angular-basic

**Comment by RonjaKnudtsen** [comment]
Yes, this is the dependencies for setting up any Angular project. But there are no details as to how to import GoJS library into Angular.

**Comment by WalterNorthwoods** [comment]
I'm not sure what you are asking for. 

$ npm i gojs

import * as go from 'gojs';
