### ISSUE TITLE
Error regarding file name casing 'DrawcommandHandler'

### ISSUE THREAD

**Issue by marcodellovo** [NorthwoodsSoftware/GoJS#69]
I'm unable to build my frontend project because of the following error:
<img width="812" alt="screenshot 2018-12-08 at 17 14 01" src="https://user-images.githubusercontent.com/26118155/49688312-3c07e900-fb10-11e8-9e0b-dd7719613b6a.png">

These are my project dependencies:
<img width="354" alt="screenshot 2018-12-08 at 17 40 33" src="https://user-images.githubusercontent.com/26118155/49688327-71143b80-fb10-11e8-98ee-b205f5f1d5eb.png">

I could solve the issue by renaming the import in the 'DrawCommandHandlerScript.ts' file but the fix will be overwritten every time I run 'npm install'.

When will this be fixed with an npm update? Is this fixed in the 2.0.0 beta?

Thanks

**Comment by WalterNorthwoods** [comment]
Thanks for catching that typo.
You should be copying only the code that you need to your own files. Those *Script.* files are just the samples, not meant for direct reuse.
