### ISSUE TITLE
commandHandler.canDeleteSelection() does not consider part.deletable property.

### ISSUE THREAD

**Issue by ilazycat** [NorthwoodsSoftware/GoJS#72]
Hi~

I found the commandHandler.canDeleteSelection() function returns true even if the selected part has deletable: false property. I dig into the code and found the definition for the commandHandler.canDeleteSelection() which as follows 

`ƒ (){var a=this.diagram;return a.isReadOnly||a.isModelReadOnly||!a.allowDelete||0===a.selection.count?!1:!0}
`

does not consider the part.deletable property at all. So I want to ask if this is the intended behavior? Cause commandHandler.canDeleteSelection() returns true on object that can not be deleted is really confusing. And it will cause some problem when I want to use this function to disable some context menu (e.g delete function) on objects that has deletable: false property. And in your [document](https://gojs.net/latest/intro/permissions.html#DeleteCommand) the delete command should consider Part.deletable property.

**Comment by simonsarris** [comment]
This is intentional, because the selection may have several `deletable` `true` parts, while others are `false`. `canDeleteSelection()` really tests if any arbitrary selection can be deleted, and does not look into which, if any of it, will actually get deleted.

**Comment by WalterNorthwoods** [comment]
To add to what Simon says, I will mention that the selected Parts are not the only Parts that may be deleted.

What if some of the (unselected) Links connected with selected Nodes have **Part.deletable** set to false?

Even more complicated, what if **CommandHandler.deletesTree** is true? I can imagine that it would be reasonable in some situations to not to allow deletions when some child node's are not deletable; but I can imagine other situations where the opposite policy is desired.

That is why you can override those methods on **CommandHandler**.
