### ISSUE TITLE
Scroll will blur canvas content

### ISSUE THREAD

**Issue by 6174** [NorthwoodsSoftware/GoJS#73]
When scroll content in gojs container, things will get blurred.  I guess it's a performance optimize strategy, but how can I disable that? 

![image](https://user-images.githubusercontent.com/3872872/54921282-5c817500-4f40-11e9-985b-f1884ea456b5.png)

**Comment by simonsarris** [comment]
You can disable it by setting the undocumented rendering hint:

```
myDiagram.setRenderingHint('temporaryPixelRatio', false);
```

Please use the [GoJS Forum](https://forum.nwoods.com/c/gojs) for questions.
