### ISSUE TITLE
Set property ‘isModified’ does not work

### ISSUE THREAD

**Issue by wx1432895954** [NorthwoodsSoftware/GoJS#82]
# problem of ‘setDataProperty’ and ‘isModified’. I do:
1. I used the method of ‘setDataProperty’ to set model data
2. then the Diagram.isModified is changed to true
3. I set the Property of ‘isModified’ false
4. but it does not work , I consoled the property of ‘isModified’ is also true
# I want to change the property and raise the listener of ‘Diagram.addDiagramListenr(‘modified’)’ after I set the Property of ‘isModified’.what can I change the property of ‘isModified’ to false success after I used the method of ‘setDataProperty’?
# Thank you very much!
[https://forum.nwoods.com/t/set-property-ismodified-does-not-work/12374](url)

**Comment by wx1432895954** [comment]
# 中文：
## 使用‘ setDataProperty’这个方法设置属性后，‘isModified’这个属性不起作用了。我是这么做的：

1. 使用setDataProperty方法设置我需要改变的值
2. diagram.ismodified属性由goJs自动更新为true
3. 我设置diagram.isModified属性为false
4. 我通过console.log(diagram.isModified)得到结果依然为true，没有成功设置为false （也就是上句的操作没有成功）

## 我想在用过setDataProperty方法改变属性后，设置isModified方法生效，并成功进入addDiagramListener('modified')的监听方法, 我该怎么做？

## 非常感谢！我的英语表达不太好，抱歉！期待解决方案！

**Comment by wx1432895954** [comment]
`
console.log(myDiagram.isModified)  // false （the diagram is not modified）
myDiagram.model.setDataProperty(nodeData, 'key',  newValue); //  (I used the method of setDataProperty to modify the key of model data)
console.log(myDiagram.isModified)  // true   (the property of isModified is changed by goJs)
myDiagram.isModified = false;  //   ( I set the property of isModified : false
console.log(myDiagram.isModified)  // true (does not work, it is also: true)

`

**Comment by simonsarris** [comment]
Please only ask questions on the [forum](https://forum.nwoods.com/t/set-property-ismodified-does-not-work/12374).
