### ISSUE TITLE
Add Generic Type for Node, Link and ...

### ISSUE THREAD

**Issue by Lavaei** [NorthwoodsSoftware/GoJS#84]
Please add Generic Type to Node (and other similar classes)  for better typing in Typescript. The generic type should represents the type of node`s data.

**Comment by WalterNorthwoods** [comment]
Thanks for the suggestion -- we'll investigate it.

**Comment by simonsarris** [comment]
Thanks. We've added this to our internal road-map to consider, so I'm closing the Github issue for now.
