### ISSUE TITLE
Property 'commitNodes' is protected and only accessible within class 'TreeLayout' and its subclasses

### ISSUE THREAD

**Issue by anuj9196** [NorthwoodsSoftware/GoJS#89]
I am followng [https://gojs.net/latest/samples/orgChartEditor.html](https://gojs.net/latest/samples/orgChartEditor.html) to learn about `GoJS`.

While overriding the `commitNodes` method of the `TreeLayout` in my Angular setup,  it is giving the error
```
TS2445: Property 'commitNodes' is protected and only accessible within class 'TreeLayout' and its subclasses
```
The example code is
```
(this.dia.layout as go.TreeLayout).commitNodes = () => {  // Error is here
      go.TreeLayout.prototype.commitNodes.call(this.dia.layout);  // and here
      // then go through all of the vertexes and set their corresponding node's Shape.fill
      // to a brush dependent on the TreeVertex.level value
      this.dia.layout.network.vertexes.each(v => {
        if (v.node) {
          const level = v.level % (this.levelColors.length);
          const color = this.levelColors[level];
          const shape = v.node.findObject('SHAPE');
          if (shape) {
            shape.stroke = $(go.Brush, 'Linear', {
              0: color,
              1: go.Brush.lightenBy(color, 0.05),
              start: go.Spot.Left,
              end: go.Spot.Right
            });
          }
        }
      });
    };
```

**Comment by WalterNorthwoods** [comment]
You can either define a sublass of **TreeLayout** or you can cast the layout as `any`.

**Comment by anuj9196** [comment]
One error is on this line https://github.com/NorthwoodsSoftware/GoJS/blob/8839499bf146f100c9f44afc5312130c65dd5e16/samples/orgChartEditor.html#L278

The API documentation does not have that method https://gojs.net/latest/api/symbols/Model.html

Webstorm gives following suggestion
```
Property 'setParentKeyForNodeData' does not exist on type 'Model'. Did you mean 'setCategoryForNodeData'?
```

**Comment by WalterNorthwoods** [comment]
That is not an error -- it is correct.  The model is actually a **TreeModel**, so that method is documented at: https://gojs.net/latest/api/symbols/TreeModel.html#setParentKeyForNodeData

I guess Webstorm could be smarter in recognizing that there are subclasses which have additional methods to consider.  Clearly that's not something that we can do anything about.
