### ISSUE TITLE
zOrder management for parts

### ISSUE THREAD

**Issue by 6174** [NorthwoodsSoftware/GoJS#91]
Hi , I am making a BPMN editor, with basic feature for zOrder management: 
- arrange bring forward 
- arrange bring front 
- arrange send backward 
- arrange send back 

I don't figure out how to make this work. Since we only have zOrder property for Part. But go model have group and group in group.   It's so complicate for user to handle all of this.  And I think it should be a basic api in go.CommandHandler.

Do you already made some example or plan for this problem?  

Thx :-)

**Comment by WalterNorthwoods** [comment]
Could you please be more precise what the problem is? Does the problem only involve Groups? Perhaps you should put all Groups in the "Background" layer and then only set **Part.zOrder** on non-Group Nodes.

**Comment by 6174** [comment]
@WalterNorthwoods  Put group in background layer is not acceptable.  What i want to do is kind of like zOrder feature in sketch layer.

**Comment by WalterNorthwoods** [comment]
You still haven't given a detailed description of the situations that you want to handle.

Putting all of the Groups in a Layer that is behind the layers where the Nodes and Links are is usually what people want.

**Comment by WalterNorthwoods** [comment]
This will be added to the **DrawCommandHandler** extension in the next release, 2.1.10:
```
  /**
   * Change the z-ordering of selected parts to pull them forward, in front of all other parts
   * in their respective layers.
   * All unselected parts in each layer with a selected Part with a non-numeric {@link Part#zOrder} will get a zOrder of zero.
   * @this {DrawCommandHandler}
   */
  public pullToFront(): void {
    const diagram = this.diagram;
    diagram.startTransaction("pullToFront");
    // find the affected Layers
    const layers = new go.Map<go.Layer, number>();
    diagram.selection.each(function(part) {
      if (part.layer !== null) layers.set(part.layer, 0);
    });
    // find the maximum zOrder in each Layer
    layers.iteratorKeys.each(function(layer) {
      let max = 0;
      layer.parts.each(function(part) {
        if (part.isSelected) return;
        const z = part.zOrder;
        if (isNaN(z)) {
          part.zOrder = 0;
        } else {
          max = Math.max(max, z);
        }
      });
      layers.set(layer, max);
    });
    // assign each selected Part.zOrder to the computed value for each Layer
    diagram.selection.each(function(part) {
      const z = layers.get(part.layer as go.Layer) || 0;
      DrawCommandHandler._assignZOrder(part, z + 1);
    });
    diagram.commitTransaction("pullToFront");
  }

  /**
   * Change the z-ordering of selected parts to push them backward, behind of all other parts
   * in their respective layers.
   * All unselected parts in each layer with a selected Part with a non-numeric {@link Part#zOrder} will get a zOrder of zero.
   * @this {DrawCommandHandler}
   */
  public pushToBack(): void {
    const diagram = this.diagram;
    diagram.startTransaction("pushToBack");
    // find the affected Layers
    const layers = new go.Map<go.Layer, number>();
    diagram.selection.each(function(part) {
      if (part.layer !== null) layers.set(part.layer, 0);
    });
    // find the minimum zOrder in each Layer
    layers.iteratorKeys.each(function(layer) {
      let min = 0;
      layer.parts.each(function(part) {
        if (part.isSelected) return;
        const z = part.zOrder;
        if (isNaN(z)) {
          part.zOrder = 0;
        } else {
          min = Math.min(min, z);
        }
      });
      layers.set(layer, min);
    });
    // assign each selected Part.zOrder to the computed value for each Layer
    diagram.selection.each(function(part) {
      const z = layers.get(part.layer as go.Layer) || 0;
      DrawCommandHandler._assignZOrder(part,
          // make sure a group's nested nodes are also behind everything else
          z - 1 - DrawCommandHandler._findGroupDepth(part));
    });
    diagram.commitTransaction("pushToBack");
  }

  private static _assignZOrder(part: go.Part, z: number, root?: go.Part): void {
    if (root === undefined) root = part;
    if (part.layer === root.layer) part.zOrder = z;
    if (part instanceof go.Group) {
      part.memberParts.each(function(m) {
        DrawCommandHandler._assignZOrder(m, z+1, root);
      });
    }
  }

  private static _findGroupDepth(part: go.Part): number {
    if (part instanceof go.Group) {
      let d = 0;
      part.memberParts.each(function(m) {
        d = Math.max(d, DrawCommandHandler._findGroupDepth(m));
      });
      return d+1;
    } else {
      return 0;
    }
  }
```

**Comment by 6174** [comment]
> This will be added to the **DrawCommandHandler** extension in the next release, 2.1.10:
> 
> ```
>   /**
>    * Change the z-ordering of selected parts to pull them forward, in front of all other parts
>    * in their respective layers.
>    * All unselected parts in each layer with a selected Part with a non-numeric {@link Part#zOrder} will get a zOrder of zero.
>    * @this {DrawCommandHandler}
>    */
>   public pullToFront(): void {
>     const diagram = this.diagram;
>     diagram.startTransaction("pullToFront");
>     // find the affected Layers
>     const layers = new go.Map<go.Layer, number>();
>     diagram.selection.each(function(part) {
>       if (part.layer !== null) layers.set(part.layer, 0);
>     });
>     // find the maximum zOrder in each Layer
>     layers.iteratorKeys.each(function(layer) {
>       let max = 0;
>       layer.parts.each(function(part) {
>         if (part.isSelected) return;
>         const z = part.zOrder;
>         if (isNaN(z)) {
>           part.zOrder = 0;
>         } else {
>           max = Math.max(max, z);
>         }
>       });
>       layers.set(layer, max);
>     });
>     // assign each selected Part.zOrder to the computed value for each Layer
>     diagram.selection.each(function(part) {
>       const z = layers.get(part.layer as go.Layer) || 0;
>       DrawCommandHandler._assignZOrder(part, z + 1);
>     });
>     diagram.commitTransaction("pullToFront");
>   }
> 
>   /**
>    * Change the z-ordering of selected parts to push them backward, behind of all other parts
>    * in their respective layers.
>    * All unselected parts in each layer with a selected Part with a non-numeric {@link Part#zOrder} will get a zOrder of zero.
>    * @this {DrawCommandHandler}
>    */
>   public pushToBack(): void {
>     const diagram = this.diagram;
>     diagram.startTransaction("pushToBack");
>     // find the affected Layers
>     const layers = new go.Map<go.Layer, number>();
>     diagram.selection.each(function(part) {
>       if (part.layer !== null) layers.set(part.layer, 0);
>     });
>     // find the minimum zOrder in each Layer
>     layers.iteratorKeys.each(function(layer) {
>       let min = 0;
>       layer.parts.each(function(part) {
>         if (part.isSelected) return;
>         const z = part.zOrder;
>         if (isNaN(z)) {
>           part.zOrder = 0;
>         } else {
>           min = Math.min(min, z);
>         }
>       });
>       layers.set(layer, min);
>     });
>     // assign each selected Part.zOrder to the computed value for each Layer
>     diagram.selection.each(function(part) {
>       const z = layers.get(part.layer as go.Layer) || 0;
>       DrawCommandHandler._assignZOrder(part,
>           // make sure a group's nested nodes are also behind everything else
>           z - 1 - DrawCommandHandler._findGroupDepth(part));
>     });
>     diagram.commitTransaction("pushToBack");
>   }
> 
>   private static _assignZOrder(part: go.Part, z: number, root?: go.Part): void {
>     if (root === undefined) root = part;
>     if (part.layer === root.layer) part.zOrder = z;
>     if (part instanceof go.Group) {
>       part.memberParts.each(function(m) {
>         DrawCommandHandler._assignZOrder(m, z+1, root);
>       });
>     }
>   }
> 
>   private static _findGroupDepth(part: go.Part): number {
>     if (part instanceof go.Group) {
>       let d = 0;
>       part.memberParts.each(function(m) {
>         d = Math.max(d, DrawCommandHandler._findGroupDepth(m));
>       });
>       return d+1;
>     } else {
>       return 0;
>     }
>   }
> ```

Thx, @WalterNorthwoods this is helpful.
