### ISSUE TITLE
Free use.

### ISSUE THREAD

**Issue by berpcor** [NorthwoodsSoftware/GoJS#92]
Hello. Is it possible to use gogojs library for internal use of company? As I understand version on github is full, the only speciality for this version is that there is watermark on the top left corner, am I right?
Somebody on github wrote that after deploying web app that uses gojs gojs stops working, is it correct information?

**Comment by WalterNorthwoods** [comment]
GitHub issues are for reporting issues (bugs) in the GoJS library, not for asking questions.
But I will answer your questions: yes, yes, no.
